
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { supabase as existingSupabaseClient } from '@/lib/supabase';

// Re-export the existing client to maintain only one instance
export const supabase = existingSupabaseClient;

// Add this comment to help developers understand how to import
// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
