// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hfffkfnpqyspnhamlzgn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhmZmZrZm5wcXlzcG5oYW1semduIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY0MzEwODQsImV4cCI6MjA2MjAwNzA4NH0.P4fD-MBA1M3wpSnc5I-hz0YyACa2TQqM_Xl1i3wgISA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);